version: '2.1'
services:
  app:
    build: .
    ports:
      - 8080:8080
    links:
    -  "mysql"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=productdemo
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
