spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productdemo?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/productdemo?useSSL=false&allowPublicKeyRetrieval=true